Script started on Thu 22 Nov 2018 05:40:32 PM PST
]0;johnatt3@zuma:hw4[johnatt3@zuma hw4]$ make
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c  DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall -c Test.c -o Test.o 
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -lm PhotoLab.o FileIO.o Test.o Image.o -L. -lFilter -o PhotoLab
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -lm PhotoLab_DEBUG.o FileIO.o Test.o Image.o -L. -lFilter -o PhotoLabTest
]0;johnatt3@zuma:hw4[johnatt3@zuma hw4]$ ./PhotoLab

----------------------------
 1:  Load a PPM image
 2:  Save an image in PPM and JPEG format
 3:  Change a color image to Black & White
 4:  Sketch the edge of an image
 5:  Shuffle an image
 6:  Adjust brightness of an image
 7:  Reflect image horizontally
 8:  Hue Rotate image
 9:  Resize image
10:  Saturate image
11:  Rotate image
12:  Test all functions
13:  Exit
Please make your choice: 12
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
hflip.ppm was saved. 
hflip.jpg was stored.
HSSOE.ppm was read.
smallresize.ppm was saved. 
smallresize.jpg was stored.
HSSOE.ppm was read.
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.

----------------------------
 1:  Load a PPM image
 2:  Save an image in PPM and JPEG format
 3:  Change a color image to Black & White
 4:  Sketch the edge of an image
 5:  Shuffle an image
 6:  Adjust brightness of an image
 7:  Reflect image horizontally
 8:  Hue Rotate image
 9:  Resize image
10:  Saturate image
11:  Rotate image
12:  Test all functions
13:  Exit
Please make your choice: 13
You exit the program.
]0;johnatt3@zuma:hw4[johnatt3@zuma hw4]$ valgrind --leak-check=full ./PhotoLabv[KTest
==24006== Memcheck, a memory error detector
==24006== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==24006== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==24006== Command: ./PhotoLabTest
==24006== 
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.
HSSOE.ppm was read.
brightness.ppm was saved. 
brightness.jpg was stored.
HSSOE.ppm was read.
hmirror.ppm was saved. 
hmirror.jpg was stored.
HSSOE.ppm was read.
hue.ppm was saved. 
hue.jpg was stored.
HSSOE.ppm was read.
rotate.ppm was saved. 
rotate.jpg was stored.
HSSOE.ppm was read.
hflip.ppm was saved. 
hflip.jpg was stored.
HSSOE.ppm was read.
smallresize.ppm was saved. 
smallresize.jpg was stored.
HSSOE.ppm was read.
bigresize.ppm was saved. 
bigresize.jpg was stored.
HSSOE.ppm was read.
saturate.ppm was saved. 
saturate.jpg was stored.
==24006== 
==24006== HEAP SUMMARY:
==24006==     in use at exit: 0 bytes in 0 blocks
==24006==   total heap usage: 78 allocs, 78 frees, 10,992,944 bytes allocated
==24006== 
==24006== All heap blocks were freed -- no leaks are possible
==24006== 
==24006== For counts of detected and suppressed errors, rerun with: -v
==24006== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;johnatt3@zuma:hw4[johnatt3@zuma hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm edge.ppm shuffle.ppm brightness.ppm hmirror.ppm hue.ppm bigresize.ppm smallresize.ppm saturate.ppm rotate.ppm hflip.ppm  libFilter.a
]0;johnatt3@zuma:hw4[johnatt3@zuma hw4]$ exit
exit

Script done on Thu 22 Nov 2018 05:41:31 PM PST
